### ISSUE TITLE
Experiencing errors on Linode when creating the qsk-book pod

### ISSUE THREAD

**Issue by pmayd** [nigelpoulton/qsk-book#5]
Hi Nigel,

I am following the exact steps of your book Quick Start Kubernetes. I am not using my own Docker image but your's.
I created the K8n cluster on Linode as described in the book and everything is working as expected, both nodes are running and green. I have pulled your code from GitHub and didn't changed a single line, just running 
`kubectl apply -f pod.yml`, which results in no error. But directly after this command the status of the Pod is 
```

NAME        READY   STATUS             RESTARTS         AGE
first-pod   0/1     CrashLoopBackOff   10 (2m29s ago)   28m
```

When I look into the logs via `kubectl logs -p first-pod` I get `exec /usr/local/bin/docker-entrypoint.sh: exec format error`. `kubectl describe` shows the following output (only the last table):

```
Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  30m                  default-scheduler  Successfully assigned default/first-pod to lke90787-137521-63de03d7609a
  Normal   Pulled     29m (x5 over 30m)    kubelet            Container image "nigelpoulton/qsk-book:1.0" already present on machine
  Normal   Created    29m (x5 over 30m)    kubelet            Created container web-ctr
  Normal   Started    29m (x5 over 30m)    kubelet            Started container web-ctr
  Warning  BackOff    25s (x141 over 30m)  kubelet            Back-off restarting failed container
```

I am not sure how to troubleshoot here and what the problem could be as the Dockerfile and app is rather simple and the cluster is healthy.

**Comment by pmayd** [comment]
OK the solution was to use the image version 1.1 for AMD64 instead of the version 1.0 which is for AMR64, as is pointed out by docker hub. But I don't understand how you could use 1.0 in the book with Linode given that I followed the exact same steps. 

So the image has to be created on the same OS which later executes the image via Docker?

**Comment by crramirez** [comment]
Probably it used to work, and Nigel inadvertently pushed a new version 2 months ago:

![image](https://user-images.githubusercontent.com/8397379/219360569-da430031-a7a1-46cb-954f-608a83b251eb.png)

**Comment by pmayd** [comment]
> Probably it used to work, and Nigel inadvertently pushed a new version 2 months ago:
> 
> ![image](https://user-images.githubusercontent.com/8397379/219360569-da430031-a7a1-46cb-954f-608a83b251eb.png)
> 

That is obvious from what I already have written as part of my solution. The main point is that it is not described in the book that the image has to be created in the same platform the containers run on Linode. So as Nigel is suggesting in his book that the reader can create their own images and just deploy them to Linode, that is just wrong and I was not aware that docker is not fully portable.

**Comment by crramirez** [comment]
Hey man, take it easy! I am just trying to help. I made the PR to fix the problem and contacted Nigel in other ways; now he is aware.

**Comment by pmayd** [comment]
I am completely calm, why do you think otherwise? As I said this is a very important finding and the book is very recently published so I was expecting some bugfix from the author in his own repository. I was able to fix it myself and even give an explanation and I also suggested to describe the codependencies in the next version of the book or at least here in the repository in the README because it is rather important when creating the image that it is also able to be run in the Linode containers.

Thanks for your help but you were not helping ;) You were just stating the obvious. The main takeaway here is that we need to explain that right now you cannot run linux/arm64 images on a Linode VM, at least I saw no option to change the Linode K8s nodes OS. So there should be a troubleshooting.md here with this case

**Comment by crramirez** [comment]
I said that because "That is obvious from what I already have written as part of my solution" my answer is not obvious, and I am helping to telling you that probably nigel uploaded this ARM64 image by mistake 2 months ago because the 1.1 is from 2 years ago

**Comment by pmayd** [comment]
And I said it's obvious because I already figured this out myself as I was stating in my solution :)

**Comment by crramirez** [comment]
Nigel just uploaded the right images for three platforms:

![image](https://user-images.githubusercontent.com/8397379/219390441-4b50c2a6-9dba-4a57-b61c-4aead061beea.png)

Regardless of the platform of your nodes, it will pick the right one.

Also, he said that if the image is already downloaded, we must force the download by adding:

```yaml
# 2022 version
apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    project: qsk-book
spec:
  containers:
    - name: web-ctr
      imagePullPolicy: Always # Add this to force refresh the bad image
      image: nigelpoulton/qsk-book:1.0
      ports:
        - containerPort: 8080

```

**Comment by pmayd** [comment]
This is really great thank you

Carlos Rafael Ramirez ***@***.***> schrieb am Do., 16. Feb.
2023, 15:24:

**Comment by crramirez** [comment]
You are very welcome

**Comment by nigelpoulton** [comment]
Added AMD64 and ARM64 images
